---
folders:
  dicom: /media/storage/cDBS/data/DICOM
  nifti: /media/storage/cDBS/data/NIFTI
  path2itksnap: /usr/lib/snap-3.6.0
  path2slicer: ''
  prefix: subj
  rootdir: /media/storage/cDBS
preprocess:
  ANTsN4:
    bspline-fitting: 200
    convergence:
    - 50
    - 50
    - 50
    - 50
    denoise: 'no'
    dti_prefix: ep2d
    prefix: bc_
    shrink-factor: 4
    threshold: 1.0e-07
  dcm2nii:
    BIDSsidecar: 'yes'
    IncludeFiles: T1_,T2_,ep2d_,H30,~SW[)],~12cha
    NameConflicts: 2
    OutputCompression: 'no'
    OutputFileStruct: '%p_%d'
    ReorientCrop: 'no'
    Verbosity: 1
  metdata: patients.xlsx
  normalisation:
    prefix: norm_
    sequences: T1_,T2_,PD_
    template_image: mni_icbm152_nlin_asym_09b
  registration:
    custom_registration_file: cmdline_ANTsRegistration.txt
    default_registration: 'yes'
    metric:
    - mattes
    - GC
    prefix: reg_
    registration_method: SyNRA
    resample_method: '0'
    resample_spacing: '0.7'
