---
folders:
  dicom: /media/storage/cDBS/data/DICOM
  nifti: /media/storage/cDBS/data/NIFTI
  path2itksnap: /usr/lib/snap-3.6.0
  path2slicer: ''
  prefix: subj
  rootdir: /media/storage/cDBS
preprocess:
  ANTsN4:
    bspline-fitting: 200
    convergence:
    - 100
    - 100
    - 100
    - 100
    denoise: 'no'
    dti_prefix: ep2d
    prefix: bc_
    shrink-factor: 4
    threshold: 1.0e-07
  Registration:
    denoise: 'no'
    dimensionality_coregister: 3
    dimensionality_denoise: 3
    resample_method: '0'
    resample_spacing: '0.7'
    use-histogram-matching: true
    winsorize-imageintensities:
    - 0.005
    - 0.005
  dcm2nii:
    BIDSsidecar: 'yes'
    IncludeFiles: T1_,T2_,ep2d_,H30,~SW[)],~12cha
    NameConflicts: 2
    OutputCompression: 'no'
    OutputFileStruct: '%p_%d'
    ReorientCrop: 'no'
    Verbosity: 1
  metdata: patients.xlsx
