# Config file saving all important settings that have been set; A recovery to default mode is possible
%YAML 1.1

---
folders:
  rootdir: ''
  dicom: ''
  nifti: ''
  path2slicer: ''
  path2itksnap: ''
  prefix: subj
preprocess:
  dcm2nii:
      BIDSsidecar: 'yes'
      OutputCompression: 'no'
      OutputFileStruct: '%p_%d'
      NameConflicts: 2
      Verbosity: 1
      IncludeFiles: "T1_,T2_,ep2d_,H30,~SW[)],~12cha"
      ReorientCrop: 'no'
  ANTsN4:
      prefix: 'bc_'
      denoise: 'no'
      shrink-factor: 4
      bspline-fitting: 200
      convergence:
        - 50
        - 50
        - 50
        - 50
      threshold: 1e-7
      dti_prefix: 'ep2d'
  registration:
      prefix: 'reg_'
      resample_spacing: 0.7
      resample_method: 2
      dimensionality_coregister: 3
      interpolation: 2
      use-histogram-matching: yes
      winsorize-imageintensities:
        - .005
        - .005
      dimensionality_denoise: 3
      apply_transformation: no
      max_iterations:
        - 1000
        - 500
        - 250
        - 100
      threshold_registration: 1e-6


  metdata: "patients.xlsx"
